cp -f "../Client/bin/Debug/net8.0/LLM.Module.LazyLoadingTest.Client.Oqtane.dll" "../../oqtane520/Oqtane.Server/bin/Debug/net8.0/"
cp -f "../Client/bin/Debug/net8.0/LLM.Module.LazyLoadingTest.Client.Oqtane.pdb" "../../oqtane520/Oqtane.Server/bin/Debug/net8.0/"
cp -f "../Server/bin/Debug/net8.0/LLM.Module.LazyLoadingTest.Server.Oqtane.dll" "../../oqtane520/Oqtane.Server/bin/Debug/net8.0/"
cp -f "../Server/bin/Debug/net8.0/LLM.Module.LazyLoadingTest.Server.Oqtane.pdb" "../../oqtane520/Oqtane.Server/bin/Debug/net8.0/"
cp -f "../Shared/bin/Debug/net8.0/LLM.Module.LazyLoadingTest.Shared.Oqtane.dll" "../../oqtane520/Oqtane.Server/bin/Debug/net8.0/"
cp -f "../Shared/bin/Debug/net8.0/LLM.Module.LazyLoadingTest.Shared.Oqtane.pdb" "../../oqtane520/Oqtane.Server/bin/Debug/net8.0/"
cp -rf "../Server/wwwroot/"* "../../oqtane520/Oqtane.Server/wwwroot/"
